name: build image
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
    paths:
      - pocketmine-mp/**

jobs:
  push:
    name: "PM${{ matrix.pmmp }} with PHP ${{ matrix.php }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3']
        pmmp: ['5']
        include:
          - php: '8.1'
            pmmp: '4'
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta  
        with:
          tags: pm${{ matrix.pmmp }}-php${{ matrix.php }}
          images: ghcr.io/superhub-host/pmmp-yolks
      - uses: docker/build-push-action@v4
        with:
          context: ./pocketmine-mp
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            PMMP_MAJOR_VERSION=${{ matrix.pmmp }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
