name: build image
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
    paths:
      - pocketmine-mp/**

jobs:
  push:
    name: "PM${{ matrix.pmmp }} with PHP ${{ matrix.php }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1']
        pmmp: ['4', '5']
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./pocketmine-mp
          push: true
          build-args: |
            PHP_VERSION=php-${{ matrix.php }}-latest
            PMMP_MAJOR_VERSION=${{ matrix.pmmp }}
          tags: |
            ghcr.io/superhub-host/ptero-pmmp:pm${{ matrix.pmmp }}-php${{ matrix.php }}
